replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

image:
  repository: daveyo89/simple-helm
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 8080
